apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../default

patches:
  - path: deployment-patches.yaml
    target:
      kind: Deployment
      name: machine-controller-manager
