apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - machine.sapcloud.io_machineclasses.yaml
  - machine.sapcloud.io_machinedeployments.yaml
  - machine.sapcloud.io_machines.yaml
  - machine.sapcloud.io_machinesets.yaml
